const ffmpeg = require('fluent-ffmpeg');
const path = require('path');
const fs = require('fs');
const Ably = require('ably');

// Set FFmpeg path to the installed location
ffmpeg.setFfmpegPath('C:\\Users\\rahul\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\\ffmpeg-8.1-full_build\\bin\\ffmpeg.exe');
ffmpeg.setFfprobePath('C:\\Users\\rahul\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\\ffmpeg-8.1-full_build\\bin\\ffprobe.exe');

class VideoProcessor {
  constructor(ably, videoId, userId) {
    this.ably = ably;
    this.videoId = videoId;
    this.userId = userId;
  }

  async processVideo(videoPath, outputPath) {
    try {
      // For Cloudinary videos, we can't process locally
      // We'll simulate processing and return basic info
      if (videoPath.includes('cloudinary')) {
        await this.emitProgress(25, 'Analyzing video...');
        
        // Simulate processing delay
        await new Promise(resolve => setTimeout(resolve, 2000));
        
        await this.emitProgress(50, 'Processing video...');
        await new Promise(resolve => setTimeout(resolve, 2000));
        
        await this.emitProgress(75, 'Analyzing sensitivity...');
        await new Promise(resolve => setTimeout(resolve, 1000));
        
        await this.emitProgress(100, 'Processing complete!');
        
        return {
          duration: Math.floor(Math.random() * 300) + 60, // Random duration between 60-360 seconds
          sensitivity: await this.analyzeSensitivity(videoPath),
          thumbnail: null // Will be generated by Cloudinary
        };
      }
      
      // Local file processing (fallback)
      await this.emitProgress(25, 'Getting video information...');
      
      // Get video duration
      const duration = await this.getVideoDuration(videoPath);
      
      await this.emitProgress(50, 'Processing video...');
      
      // Generate thumbnail (if local)
      const thumbnailPath = await this.generateThumbnail(videoPath, outputPath);
      
      await this.emitProgress(75, 'Analyzing sensitivity...');
      
      // Analyze sensitivity
      const sensitivity = await this.analyzeSensitivity(videoPath);
      
      await this.emitProgress(100, 'Processing complete!');
      
      return {
        duration,
        thumbnail: thumbnailPath,
        sensitivity
      };
    } catch (error) {
      console.error('Video processing error:', error);
      throw error;
    }
  }

  async getVideoDuration(videoPath) {
    return new Promise((resolve, reject) => {
      ffmpeg.ffprobe(videoPath, (err, metadata) => {
        if (err) {
          console.error('Error getting video duration:', err);
          resolve(0); // Default duration if error
          return;
        }
        
        const duration = metadata.format.duration;
        resolve(Math.floor(duration));
      });
    });
  }

  async generateThumbnail(videoPath, outputPath) {
    // For Cloudinary, thumbnail is generated separately
    if (videoPath.includes('cloudinary')) {
      return null;
    }
    
    return new Promise((resolve, reject) => {
      const thumbnailPath = path.join(path.dirname(outputPath), 'thumbnail.jpg');
      
      ffmpeg(videoPath)
        .screenshots({
          timestamps: ['10%'],
          filename: path.basename(thumbnailPath),
          folder: path.dirname(thumbnailPath),
          size: '320x240'
        })
        .on('end', () => resolve(thumbnailPath))
        .on('error', (err) => {
          console.error('Error generating thumbnail:', err);
          resolve(null); // Return null if error
        });
    });
  }

  async analyzeSensitivity(videoPath) {
    // Simulate sensitivity analysis
    // In a real application, you might use AI/ML models here
    return new Promise((resolve) => {
      // Simple simulation based on file size or random logic
      const isFlagged = Math.random() > 0.8;
      
      resolve(isFlagged ? 'flagged' : 'safe');
    });
  }

  async emitProgress(progress, message) {
    try {
      const channel = this.ably.channels.get(`user-${this.userId}`);
      await channel.publish('video-processing-progress', {
        videoId: this.videoId,
        progress,
        message,
        timestamp: new Date().toISOString()
      });
    } catch (error) {
      console.error('Failed to emit progress to Ably:', error);
    }
  }
}

module.exports = VideoProcessor;
